version: "3.7"

# https://accesso.sova.dev

services:
  traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./services/traefik/config.yml:/etc/traefik/config.yml:ro
    labels:
      traefik.http.routers.traefik-secure.tls.certresolver: "le"
      traefik.http.routers.traefik-secure.middlewares: "dashboard-auth@file"

  grafana:
    labels:
      traefik.http.routers.grafana.tls.certresolver: "le"

  api-internal:
    image: ghcr.io/accesso-app/backend/api-internal:latest
    environment:
      ACCESSO_SENDGRID__APPLICATION_HOST: accesso.sova.dev
      ACCESSO_SENDGRID__SENDER_EMAIL: no-reply@accesso.sova.dev
      ACCESSO_SENDGRID__ENABLED: "true"
    labels:
      traefik.http.routers.traefik.tls.certresolver: "le"

  api-admin:
    image: ghcr.io/accesso-app/backend/api-admin:latest
    environment:
      ACCESSO_SENDGRID__APPLICATION_HOST: accesso.sova.dev
      ACCESSO_SENDGRID__SENDER_EMAIL: no-reply@accesso.sova.dev
      ACCESSO_SENDGRID__ENABLED: "true"
    labels:
      traefik.http.routers.traefik.tls.certresolver: "le"
      traefik.http.routers.traefik-secure.middlewares: "admin-auth@file"

  api-public:
    image: ghcr.io/accesso-app/backend/api-public:latest
    environment:
      ACCESSO_SENDGRID__APPLICATION_HOST: accesso.sova.dev
      ACCESSO_SENDGRID__SENDER_EMAIL: no-reply@accesso.sova.dev
    labels:
      traefik.http.routers.api-public.tls.certresolver: "le"

  admin:
    image: ghcr.io/accesso-app/admin/frontend:latest
    environment:
      PUBLIC_URL: https://admin.accesso.sova.dev
    labels:
      traefik.http.routers.admin.tls.certresolver: "le"
      traefik.http.routers.traefik-secure.middlewares: "admin-auth@file"

  frontend:
    image: ghcr.io/accesso-app/frontend/main:latest
    labels:
      traefik.http.routers.frontend.tls.certresolver: "le"
    environment:
      PUBLIC_URL: https://accesso.sova.dev
      IMAGE_URL: https://accesso.sova.dev/images
      DEBUG: "true"
