version: "3.7"

# https://auth-dev.atomix.team

# mkdir -p /usr/local/var/authmenow/images
##
## issue certificate with let's encrypt
# mkdir -p /usr/local/var/authmenow/tls
# openssl dhparam -out /usr/local/var/authmenow/tls/dhparam.pem 2048

## Latest deploy: 2020-02-21T16:28:28.294Z2

volumes:
  image-storage:
    driver: local
    driver_opts:
      type: none
      device: "/usr/local/var/authmenow/images"
      o: bind

services:
  database:
    volumes:
      - /usr/local/var/authmenow/postgres:/var/lib/postgresql/data

  public-api:
    image: "docker.pkg.github.com/authmenow/backend/public-api:0"

  frontend:
    image: "docker.pkg.github.com/authmenow/frontend/frontend:0"
    networks:
      entry:
        aliases:
          - auth-dev.atomix.team
    volumes:
      - /etc/letsencrypt/live/auth-dev.atomix.team/fullchain.pem:/var/lib/authmenow/tls/authmenow.crt
      - /etc/letsencrypt/live/auth-dev.atomix.team/privkey.pem:/var/lib/authmenow/tls/authmenow.pem
      - /usr/local/var/authmenow/tls/dhparam.pem:/etc/ssl/certs/dhparam.pem

  # admin:
  #   image: docker.pkg.github.com/authmenow/admin/admin:dev
