version: "3.7"

# https://accesso.sova.dev

# mkdir -p /usr/local/var/accesso/images
##
## issue one certificate with let's encrypt
## for accesso.sova.dev
#
# mkdir -p /usr/local/var/accesso/tls
# openssl dhparam -out /usr/local/var/accesso/tls/dhparam.pem 2048

volumes:
  image-storage:
    driver: local
    driver_opts:
      type: none
      device: "/usr/local/var/accesso/images"
      o: bind

services:
  database:
    volumes:
      - /usr/local/var/accesso/postgres:/var/lib/postgresql/data

  api-public:
    image: "docker.pkg.github.com/accesso-app/backend/api-public:latest"
    environment:
      SG_APPLICATION_HOST: accesso.sova.dev
      SG_SENDER_EMAIL: no-reply@accesso.sova.dev

  api-internal:
    image: "docker.pkg.github.com/accesso-app/backend/api-internal:latest"
    environment:
      SG_APPLICATION_HOST: accesso.sova.dev
      SG_SENDER_EMAIL: no-reply@accesso.sova.dev

  frontend:
    image: "docker.pkg.github.com/accesso-app/frontend/main:latest"
    environment:
      PUBLIC_URL: https://accesso.sova.dev
      IMAGE_URL: https://accesso.sova.dev/images
      DEBUG: "true"

  facade:
    image: "docker.pkg.github.com/accesso-app/releases/facade:latest"
    networks:
      entry:
        aliases:
          - accesso.sova.dev
    volumes:
      - /etc/letsencrypt/live/accesso.sova.dev/fullchain.pem:/var/lib/accesso/tls/accesso.crt:ro
      - /etc/letsencrypt/live/accesso.sova.dev/privkey.pem:/var/lib/accesso/tls/accesso.pem:ro
      - /usr/local/var/accesso/tls/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - image-storage:/images
    environment:
      SERVER_NAME: accesso.sova.dev
      WEB_EXTRA: if ($$request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
        }
        if ($$request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        }
