version: "3.7"

# https://accesso.sova.dev

services:
  traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./services/traefik/config.yml:/etc/traefik/config.yml:ro
      - ./letsencrypt:/letsencrypt
    labels:
      traefik.http.routers.traefik.tls.certresolver: "le"
      #traefik.http.routers.traefik.middlewares: "dashboard-auth@file"

  grafana:
    labels:
      traefik.http.routers.grafana.tls.certresolver: "le"

  api-internal:
    image: "docker.pkg.github.com/accesso-app/backend/api-internal:latest"
    environment:
      ACCESSO_SENDGRID__APPLICATION_HOST: accesso.sova.dev
      ACCESSO_SENDGRID__SENDER_EMAIL: no-reply@accesso.sova.dev
    labels:
      traefik.http.routers.traefik.tls.certresolver: "le"

  api-public:
    image: "docker.pkg.github.com/accesso-app/backend/api-public:latest"
    environment:
      ACCESSO_SENDGRID__APPLICATION_HOST: accesso.sova.dev
      ACCESSO_SENDGRID__SENDER_EMAIL: no-reply@accesso.sova.dev
    labels:
      traefik.http.routers.api-public.tls.certresolver: "le"

  frontend:
    image: "docker.pkg.github.com/accesso-app/frontend/main:latest"
    labels:
      traefik.http.routers.frontend.tls.certresolver: "le"
    environment:
      PUBLIC_URL: https://accesso.sova.dev
      IMAGE_URL: https://accesso.sova.dev/images
      DEBUG: "true"
