version: "3.7"

# https://auth-dev.atomix.team

# mkdir -p /usr/local/var/authmenow/images
##
## issue certificate with let's encrypt
# mkdir -p /usr/local/var/authmenow/tls
# openssl dhparam -out /usr/local/var/authmenow/tls/dhparam.pem 2048

## Latest manual deploy: 2020-04-08T08:22:12.257Z

volumes:
  image-storage:
    driver: local
    driver_opts:
      type: none
      device: "/usr/local/var/authmenow/images"
      o: bind

services:
  database:
    volumes:
      - /usr/local/var/authmenow/postgres:/var/lib/postgresql/data

  public-api:
    image: "docker.pkg.github.com/authmenow/backend/public-api:latest"

  frontend:
    image: "docker.pkg.github.com/authmenow/frontend/main:latest"
    environment:
      PUBLIC_URL: https://auth-dev.atomix.team
      IMAGE_URL: https://auth-dev.atomix.team/images
      DEBUG: "true"

  facade:
    image: "docker.pkg.github.com/authmenow/releases/facade:latest"
    networks:
      entry:
        aliases:
          - auth-dev.atomix.team
    volumes:
      - /etc/letsencrypt/live/auth-dev.atomix.team/fullchain.pem:/var/lib/authmenow/tls/authmenow.crt:ro
      - /etc/letsencrypt/live/auth-dev.atomix.team/privkey.pem:/var/lib/authmenow/tls/authmenow.pem:ro
      - /usr/local/var/authmenow/tls/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - image-storage:/images
    environment:
      SERVER_NAME: auth-dev.atomix.team
  # admin:
  #   image: docker.pkg.github.com/authmenow/admin/admin:dev
