version: "3.7"

# https://auth-dev.atomix.team

# mkdir -p /usr/local/var/accesso/images
##
## issue certificate with let's encrypt
# mkdir -p /usr/local/var/accesso/tls
# openssl dhparam -out /usr/local/var/accesso/tls/dhparam.pem 2048

## Latest manual deploy: 2020-07-03T15:55:22.409Z

volumes:
  image-storage:
    driver: local
    driver_opts:
      type: none
      device: "/usr/local/var/accesso/images"
      o: bind

services:
  database:
    volumes:
      - /usr/local/var/accesso/postgres:/var/lib/postgresql/data

  public-api:
    image: "docker.pkg.github.com/accesso-app/backend/public-api:latest"
    environment:
      SG_APPLICATION_HOST: auth-dev.atomix.team
      SG_SENDER_EMAIL: no-reply@auth-dev.atomix.team

  frontend:
    image: "docker.pkg.github.com/accesso-app/frontend/main:latest"
    environment:
      PUBLIC_URL: https://auth-dev.atomix.team
      IMAGE_URL: https://auth-dev.atomix.team/images
      DEBUG: "true"

  facade:
    image: "docker.pkg.github.com/accesso-app/releases/facade:latest"
    networks:
      entry:
        aliases:
          - auth-dev.atomix.team
    volumes:
      - /etc/letsencrypt/live/auth-dev.atomix.team/fullchain.pem:/var/lib/accesso/tls/accesso.crt:ro
      - /etc/letsencrypt/live/auth-dev.atomix.team/privkey.pem:/var/lib/accesso/tls/accesso.pem:ro
      - /usr/local/var/accesso/tls/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - image-storage:/images
    environment:
      SERVER_NAME: auth-dev.atomix.team
      WEB_EXTRA: if ($$request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
        }
        if ($$request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
        }

  # admin:
  #   image: docker.pkg.github.com/accesso-app/admin/admin:dev
