version: "3.7"

# https://accesso.app

# mkdir -p /mnt/volume_nyc1_01/accesso/images
# mkdir -p /mnt/volume_nyc1_01/accesso/postgres
# mkdir -p /mnt/volume_nyc1_01/accesso/webroot
##
## issue one certificate with let's encrypt
## for accesso.app
#
# mkdir -p /usr/local/var/accesso/tls
# openssl dhparam -out /usr/local/var/accesso/tls/dhparam.pem 2048

volumes:
  image-storage:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/volume_nyc1_01/accesso/images"
      o: bind

  facade-webroot:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/volume_nyc1_01/accesso/webroot"
      o: bind

  tls-storage:
    driver: local
    driver_opts:
      type: none
      device: "/usr/local/var/accesso/tls"
      o: bind

services:
  database:
    volumes:
      - /mnt/volume_nyc1_01/accesso/postgres:/var/lib/postgresql/data

  traefik:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./services/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./services/traefik/config.yml:/etc/traefik/config.yml:ro
      - tls-storage:/tls
    labels:
      traefik.http.routers.traefik-secure.tls.certresolver: "le"
      traefik.http.routers.traefik-secure.middlewares: "dashboard-auth@file"

  grafana:
    labels:
      traefik.http.routers.grafana.tls.certresolver: "le"

  api-internal:
    image: "ghcr.io/accesso-app/backend/api-internal:latest"
    environment:
      ACCESSO_SENDGRID__APPLICATION_HOST: accesso.app
      ACCESSO_SENDGRID__SENDER_EMAIL: no-reply@accesso.app
      ACCESSO_SENDGRID__ENABLED: "true"
    labels:
      traefik.http.routers.traefik.tls.certresolver: "le"

  api-public:
    image: "ghcr.io/accesso-app/backend/api-public:latest"
    environment:
      ACCESSO_SENDGRID__APPLICATION_HOST: accesso.app
      ACCESSO_SENDGRID__SENDER_EMAIL: no-reply@accesso.app
    labels:
      traefik.http.routers.api-public.tls.certresolver: "le"

  api-admin:
    image: "ghcr.io/accesso-app/backend/api-admin:latest"
    environment:
      ACCESSO_SENDGRID__APPLICATION_HOST: accesso.app
      ACCESSO_SENDGRID__SENDER_EMAIL: no-reply@accesso.app
      ACCESSO_SENDGRID__ENABLED: "true"
    labels:
      traefik.http.routers.api-admin.tls.certresolver: "le"
      traefik.http.routers.api-admin.middlewares: "api-admin-stripprefix@file, admin-auth@file"

  frontend:
    image: "ghcr.io/accesso-app/frontend/main:latest"
    labels:
      traefik.http.routers.frontend.tls.certresolver: "le"
    environment:
      PUBLIC_URL: https://accesso.app
      IMAGE_URL: https://accesso.app/images

  admin:
    image: "ghcr.io/accesso-app/admin/frontend:latest"
    environment:
      PUBLIC_URL: https://admin.accesso.app
    labels:
      traefik.http.routers.admin-secure.tls.certresolver: "le"
      traefik.http.routers.admin-secure.middlewares: "admin-auth@file"
      traefik.http.routers.admin.middlewares: "admin-auth@file"
