version: "3.7"

# https://accesso.app

# mkdir -p /mnt/volume_nyc1_01/accesso/images
# mkdir -p /mnt/volume_nyc1_01/accesso/postgres
# mkdir -p /mnt/volume_nyc1_01/accesso/webroot
##
## issue one certificate with let's encrypt
## for accesso.app
#
# mkdir -p /usr/local/var/accesso/tls
# openssl dhparam -out /usr/local/var/accesso/tls/dhparam.pem 2048

volumes:
  image-storage:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/volume_nyc1_01/accesso/images"
      o: bind

  facade-webroot:
    driver: local
    driver_opts:
      type: none
      device: "/mnt/volume_nyc1_01/accesso/webroot"
      o: bind

services:
  database:
    volumes:
      - /mnt/volume_nyc1_01/accesso/postgres:/var/lib/postgresql/data

  api-internal:
    image: "docker.pkg.github.com/accesso-app/backend/api-internal:sha-da0450d"
    environment:
      # TODO: rename to ACCESSO_SENDGRID__APPLICATION_HOST
      SG_APPLICATION_HOST: accesso.app
      # TODO: rename to ACCESSO_SENDGRID__SENDER_EMAIL
      SG_SENDER_EMAIL: no-reply@accesso.app

  api-public:
    image: "docker.pkg.github.com/accesso-app/backend/api-public:sha-da0450d"
    environment:
      # TODO: rename to ACCESSO_SENDGRID__APPLICATION_HOST
      SG_APPLICATION_HOST: accesso.app
      # TODO: rename to ACCESSO_SENDGRID__SENDER_EMAIL
      SG_SENDER_EMAIL: no-reply@accesso.app

  frontend:
    image: "docker.pkg.github.com/accesso-app/frontend/main:0.2.1"
    environment:
      PUBLIC_URL: https://accesso.app
      IMAGE_URL: https://accesso.app/images

  facade:
    image: "docker.pkg.github.com/accesso-app/releases/facade:0.2.0"
    networks:
      entry:
        aliases:
          - accesso.app
    volumes:
      - /etc/letsencrypt/live/accesso.app/fullchain.pem:/var/lib/accesso/tls/accesso.crt:ro
      - /etc/letsencrypt/live/accesso.app/privkey.pem:/var/lib/accesso/tls/accesso.pem:ro
      - /usr/local/var/accesso/tls/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
      - image-storage:/images
      - facade-webroot:/webroot
    environment:
      SERVER_NAME: accesso.app
      WEB_EXTRA: ''
