http:
  middlewares:
    api-internal-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/internal"
    api-public-stripprefix:
      stripPrefix:
        prefixes:
          - "/v0"
    admin-auth:
      basicAuth:
        users:
          - "sergeysova:$$apr1$$nJ2RVxl1$$lctgmatAl4DGCx2UZE7YD1"
    api-admin-stripprefix:
      stripPrefix:
        prefixes:
          - "/api"
    security-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        isDevelopment: false

tls:
  certificates:
    - certFile: "/tls/accesso-local.cert"
      keyFile: "/tls/accesso-local.pem"