http:
  middlewares:
    api-internal-stripprefix:
      stripPrefix:
        prefixes:
          - "/api/internal"
    api-public-stripprefix:
      stripPrefix:
        prefixes:
          - "/v0"

tls:
  certificates:
    - certFile: "/etc/tls/accesso-local.cert"
      keyFile: "/etc/tls/accesso-local.pem"